version: '3.4'

volumes:
  maria-data:
  esdata:

services:
  maria:
    image: mariadb:10.3.28
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=makawatch
    volumes:
      - maria-data:/var/lib/mysql:rw
    ports:
      - '3307:3306'

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"

